version: "3"

services:
  backend:
    # image: comic-grpc-web-backend:v0.0.1
    build:
      context: ./backend/
      dockerfile: ./Dockerfile

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"

  proxy:
    build:
      context: ./proxy/
      dockerfile: ./Dockerfile
    links:
      - backend
    ports:
      - "8080:8080"
