version: "3"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    environment:
      - APP_DATABASE_HOST=mongo
      - APP_DATABASE_PORT=27017
      - APP_DATABASE_NAME=comic-service-db
      - APP_SERVER_PORT=8080
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"

  proxy:
    build:
      context: ./proxy/
      dockerfile: ./Dockerfile
    environment:
      - GRPC_SERVER_HOST=backend
      - GRPC_SERVER_PORT=8080
    links:
      - backend
    ports:
      - "8080:8080"

  mongo:
    image: mongo:3.6

  mongo-seeder:
    build:
      context: ./mongo-seeder/
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=comic-service-db
    links:
      - mongo
    depends_on:
      - mongo
