// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/utility.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Paging struct {
	HasNext              bool     `protobuf:"varint,1,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	HasPrevious          bool     `protobuf:"varint,3,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	Previous             string   `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_a74e980e9813db3b, []int{0}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *Paging) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *Paging) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *Paging) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func init() {
	proto.RegisterType((*Paging)(nil), "ggarry9424.comic_web.Paging")
}

func init() { proto.RegisterFile("protobuf/utility.proto", fileDescriptor_a74e980e9813db3b) }

var fileDescriptor_a74e980e9813db3b = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x2d, 0xc9, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x03, 0x0b, 0x08,
	0x89, 0xa4, 0xa7, 0x27, 0x16, 0x15, 0x55, 0x5a, 0x9a, 0x18, 0x99, 0xe8, 0x25, 0xe7, 0xe7, 0x66,
	0x26, 0xc7, 0x97, 0xa7, 0x26, 0x29, 0x95, 0x70, 0xb1, 0x05, 0x24, 0xa6, 0x67, 0xe6, 0xa5, 0x0b,
	0x49, 0x70, 0xb1, 0x67, 0x24, 0x16, 0xfb, 0xa5, 0x56, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x04, 0xc1, 0xb8, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x20, 0x61, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x30, 0x5b, 0x48, 0x81, 0x8b, 0x3b, 0x23, 0xb1, 0x38, 0xa0, 0x28, 0xb5, 0x2c, 0x33, 0xbf, 0xb4,
	0x58, 0x82, 0x19, 0xac, 0x03, 0x59, 0x48, 0x48, 0x8a, 0x8b, 0xa3, 0x00, 0x26, 0xcd, 0x02, 0xd6,
	0x09, 0xe7, 0x3b, 0x71, 0x45, 0x71, 0xc0, 0x5c, 0x99, 0xc4, 0x06, 0x66, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x74, 0x70, 0x94, 0x7a, 0xb8, 0x00, 0x00, 0x00,
}
