/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ggarry9424.comic_web.Paging', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ggarry9424.comic_web.Paging = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ggarry9424.comic_web.Paging, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ggarry9424.comic_web.Paging.displayName = 'proto.ggarry9424.comic_web.Paging';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ggarry9424.comic_web.Paging.prototype.toObject = function(opt_includeInstance) {
  return proto.ggarry9424.comic_web.Paging.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ggarry9424.comic_web.Paging} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ggarry9424.comic_web.Paging.toObject = function(includeInstance, msg) {
  var obj = {
    hasnext: jspb.Message.getFieldWithDefault(msg, 1, false),
    next: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hasprevious: jspb.Message.getFieldWithDefault(msg, 3, false),
    previous: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ggarry9424.comic_web.Paging}
 */
proto.ggarry9424.comic_web.Paging.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ggarry9424.comic_web.Paging;
  return proto.ggarry9424.comic_web.Paging.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ggarry9424.comic_web.Paging} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ggarry9424.comic_web.Paging}
 */
proto.ggarry9424.comic_web.Paging.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasnext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNext(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasprevious(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrevious(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ggarry9424.comic_web.Paging.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ggarry9424.comic_web.Paging.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ggarry9424.comic_web.Paging} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ggarry9424.comic_web.Paging.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHasnext();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getNext();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHasprevious();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPrevious();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional bool hasNext = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ggarry9424.comic_web.Paging.prototype.getHasnext = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.ggarry9424.comic_web.Paging.prototype.setHasnext = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string next = 2;
 * @return {string}
 */
proto.ggarry9424.comic_web.Paging.prototype.getNext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ggarry9424.comic_web.Paging.prototype.setNext = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool hasPrevious = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ggarry9424.comic_web.Paging.prototype.getHasprevious = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.ggarry9424.comic_web.Paging.prototype.setHasprevious = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string previous = 4;
 * @return {string}
 */
proto.ggarry9424.comic_web.Paging.prototype.getPrevious = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ggarry9424.comic_web.Paging.prototype.setPrevious = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.ggarry9424.comic_web);
